// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Deveventhings.DbEntities.DbEntities
{
    public partial class tcoreuserrole
    {
        [Key]
        public int id { get; set; }
        public int user_id { get; set; }
        public int role_id { get; set; }
        public int active { get; set; }
        public int is_deleted { get; set; }
        [StringLength(256)]
        public string created_by { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? created_at { get; set; }
        [StringLength(256)]
        public string updated_by { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? updated_at { get; set; }

        [ForeignKey(nameof(role_id))]
        [InverseProperty(nameof(tcorerole.tcoreuserrole))]
        public virtual tcorerole role_ { get; set; }
        [ForeignKey(nameof(user_id))]
        [InverseProperty(nameof(tcoreuser.tcoreuserrole))]
        public virtual tcoreuser user_ { get; set; }
    }
}