// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Deveventhings.DbEntities.DbEntities
{
    public partial class tcorewallet
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(256)]
        public string user_id { get; set; }
        [Column(TypeName = "decimal(19, 4)")]
        public decimal? prev_balance { get; set; }
        [Column(TypeName = "decimal(19, 4)")]
        public decimal? amount_paid { get; set; }
        [Column(TypeName = "decimal(19, 4)")]
        public decimal? current_balance { get; set; }
        public int active { get; set; }
        public int is_deleted { get; set; }
        [StringLength(256)]
        public string created_by { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? created_at { get; set; }
        [StringLength(256)]
        public string updated_by { get; set; }
        [Column(TypeName = "datetime2(0)")]
        public DateTime? updated_at { get; set; }
    }
}