// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Eventhings.Dto
{
    public partial class TmstrCodeStoreRequest
    {
        public int id { get; set; }
        public string batch_number { get; set; }
        public string batcg_name { get; set; }
        public string code { get; set; }
        public int? encrypted_code { get; set; }
        public int active { get; set; }
        public DateTime? date_used { get; set; }
        public int is_deleted { get; set; }
    }
}